version: "2"
services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: content-service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data/pgdata
