#!/usr/bin/env node

const pg = require('pg');
const environment = process.env.ENV || 'dev';
console.log(`Launching database from ${environment}`);
const dbConfig = require('../database.json')[environment];


let timedOut = false;

function timeout(seconds) {
  console.log('timeout started');
  setTimeout(function() {
    timedOut = true;
  }, seconds * 1000);
}


function tryConnect() {
  return new Promise((resolve, reject) => {
    console.log('trying connection...');
    const client = new pg.Client(dbConfig);
    client.connect(function(err) {
      if (!err) {
        console.log("Connected");
        resolve();
      } else {
        console.log('connect error...');
        if (timedOut) {
          console.log('timed out');
          reject('timed out');
        } else {
          console.log('trying again');
          setTimeout(function() {
            resolve(tryConnect());
          }, 1000);
        }
      }
    });
  });
}

(function start() {
  timeout(300);
  tryConnect()
  .then(() => {
    process.exit(0);
  })
  .catch(() => {
    process.exit(1);
  });
}());
