#!/usr/bin/env node

const pg = require('pg');
const environment = process.env.ENV || 'dev';
console.log(`Launching database from ${environment}`);
const dbConfig = require('../database.json')[environment];

const client = new pg.Client(dbConfig);

let timedOut = false;

function timeout(seconds) {
  setTimeout(function() {
    timedOut = true;
  }, seconds * 1000);
}


function tryConnect() {
  return new Promise((resolve, reject) => {
    client.connect(function(err) {
      if (!err) {
        console.log("Connected");
        resolve();
      } else {
        if (timedOut) {
          reject('timed out');
        } else {
          console.log('trying again');
          tryConnect();
        }
      }
    });
  });
}

(function start() {
  timeout(30);
  tryConnect()
  .then(() => {
    process.exit(0);
  })
  .catch(() => {
    process.exit(1);
  });
}());
