version: '2'
services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: content-service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data/pgdata
  content:
    build:
      context: ./content-service
    depends_on:
      - db
    links:
      - db
    ports:
      - "3000:3000"
  shortener:
    build:
      context: ./magnet-shortener
    depends_on:
      - content
    links:
      - content
    ports:
      - "3001:8080"
  metadata:
    build:
      context: ./magnet-metadata-service
    ports:
      - "3002:3000"
